name: ai-bank-app-workflow
on:
 workflow_dispatch:
jobs:
 deploy-app:
  runs-on: ubuntu-latest
  steps:
    - name: checkout code
      uses: actions/checkout@v4
    - name: build docker image
      run: docker build -t ai-bank-app:latest .
    - name: docker login
      env:
       DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
       DOCKERHUB_TOKEN:  ${{ secrets.DOCKERHUB_TOKEN }}
      run: |
       echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
    - name: Get short SHA
      run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV
    - name: tag the image
      run: |
        docker tag ai-bank-app:latest ${{ secrets.DOCKERHUB_USERNAME }}/ai-bank-app:latest
        docker tag ai-bank-app:latest ${{ secrets.DOCKERHUB_USERNAME }}/ai-bank-app:sha-$SHORT_SHA
    - name: push the image
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/ai-bank-app:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/ai-bank-app:sha-$SHORT_SHA
    
        
       
        
